### ISSUE TITLE
add `astro upgrade` command

### ISSUE THREAD

**Issue by neel-astro** [astro-projects/astro-cli#20]
To add `astro upgrade` command to astro-cli, which will check if there is any new release for `astro-cli` available.

**Comment by neel-astro** [comment]
@sunkickr do we want to name it as does naming the command as `upgrade-check` makes more sense,? currently it is `astro version upgrade` in current CLI.

**Comment by sunkickr** [comment]
I think upgrade-check is fine

**Comment by kushalmalani** [comment]
Migrating this ticket to astro-cli repo. New ticket is linked
